# docker-compose.yml
version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: deployment/api.docker
    ports:
      - "4201:4201"
    volumes:
      - ../db:/app/db
    environment:
      - FLASK_ENV=production
      - CHROMADB_PATH=/app/db

  frontend:
    build:
      context: ..
      dockerfile: deployment/front.docker
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  db_data: