# docker-compose.yml
version: '3.8'

services:
  cocktail:
    build:
      context: ..
      dockerfile: deployment/cocktail.dockerfile
    ports:
      - "80:80"
    volumes:
      - ../db:/app/db
    environment:
      - FLASK_ENV=production
      - CHROMADB_PATH=/app/db