# .github/workflows/deploy.yml
name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to ACR
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
    
    - name: Build and push Docker image
      run: |
        docker build -f deployment/cocktail.dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/cocktails-combined:${{ github.sha }} .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/cocktails-combined:${{ github.sha }}
      env:
        ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    
    - name: Upload ChromaDB data
      run: |
        pip install azure-storage-file
        python deployment/scripts/upload_initial_db.py
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
    
    - name: Deploy to Azure Web Apps
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cocktails-app'
        images: ${{ secrets.ACR_LOGIN_SERVER }}/cocktails-combined:${{ github.sha }}